source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CTImagePicker_Example', :exclusive => true do
  pod "CTImagePicker", :path => "../"
end

target 'CTImagePicker_Tests', :exclusive => true do
  pod "CTImagePicker", :path => "../"

  
end
